export interface LocalityMap {
  [city: string]: string[];
}

export interface StateLocationData {
  state: string;
  cities: {
    [cityName: string]: string[];
  };
}

export const NORTHEAST_LOCATIONS: Record<string, Record<string, string[]>> = {
  Assam: {
    Guwahati: [
      "GS Road",
      "Zoo Road (RG Baruah Rd)",
      "Dispur & Capital Complex",
      "Khanapara & Koinadhara",
      "Ganeshguri",
      "Six Mile & Chachal",
      "Beltola & Survey",
      "Paltan Bazaar & Railway Station",
      "Panbazar & Fancy Bazaar",
      "Chandmari & Silpukhuri",
      "Jalukbari & Gauhati University",
      "Maligaon & Kamakhya",
      "Hatigaon & Bhetapara",
      "Ulubari & Lachit Nagar",
      "Uzanbazar & Kharghuli",
      "Bhangagarh & GMCH",
      "Kahilipara & Jatia",
      "Lokhra & Lalganesh",
      "VIP Road & Borbari",
      "Narengi & Forest Gate",
      "Rehabari & Arya Nagar",
      "North Guwahati / IIT Area",
      "Borjhar & Airport Area",
      "Other Locality / Area",
    ],
    Dibrugarh: [
      "Thana Chariali",
      "Chowkidinghee",
      "Graham Bazar",
      "Mancotta Road",
      "Amolapatty",
      "Boiragimoth",
      "Naliapool",
      "Dibrugarh University Area",
      "Milan Nagar",
      "Other Locality / Area",
    ],
    Jorhat: [
      "Gar-Ali",
      "AT Road",
      "Tarajan",
      "KB Road",
      "Na-Ali",
      "Baghsong (AAU Area)",
      "Barbheta",
      "Kenduguri",
      "Jorhat Court Area",
      "Other Locality / Area",
    ],
    Silchar: [
      "Premtala",
      "Goldighi Mall Area",
      "Tarapur",
      "Rongpur",
      "Ambicapatty",
      "Rangirkhari",
      "Hospital Road",
      "National Highway Point",
      "Other Locality / Area",
    ],
    Tezpur: [
      "Mission Chariali",
      "Tribeni",
      "Mahabhairab",
      "Chitralekha Udyan Area",
      "Dekargaon",
      "Tezpur University (Napaam)",
      "Collegiate Area",
      "Other Locality / Area",
    ],
    Nagaon: [
      "Haibargaon",
      "Barabazar",
      "Christian Patty",
      "Khutikatia",
      "Faujdaripatty",
      "Panigaon",
      "Other Locality / Area",
    ],
    Tinsukia: [
      "GNB Road",
      "Chirwapatty",
      "Borguri",
      "Nau-Pukhuri",
      "Hijuguri",
      "Sripuria",
      "Other Locality / Area",
    ],
    Sualkuchi: [
      "Silk Weavers Colony",
      "Main Bazar",
      "Bhattapara",
      "Ghat Road",
      "Other Locality / Area",
    ],
    Barpeta: [
      "Satra Area",
      "Barpeta Town Bazar",
      "Kayapatty",
      "Barpeta Road",
      "Howly",
      "Other Locality / Area",
    ],
    Bongaigaon: [
      "Chapaguri",
      "Mayapuri",
      "New Bongaigaon Railway Colony",
      "Dhaligaon (BGR Area)",
      "Borpara",
      "Other Locality / Area",
    ],
    Sivasagar: [
      "Boarding Field Area",
      "Amolapatty",
      "Station Road",
      "Joysagar",
      "Sivasagar Town",
      "Other Locality / Area",
    ],
    Golaghat: [
      "Main Town",
      "Amolapatty",
      "Circuit House Road",
      "Bokakhat",
      "Dergaon",
      "Other Locality / Area",
    ],
    Karimganj: [
      "Station Road",
      "Main Market",
      "Subhas Nagar",
      "Longai Road",
      "Badarpur",
      "Other Locality / Area",
    ],
    "North Lakhimpur": [
      "CD Road",
      "Main Chariali",
      "Khelmati",
      "Saboti",
      "Other Locality / Area",
    ],
    Dhubri: [
      "Boro Bazar",
      "GTB Road",
      "Gauripur",
      "College Road",
      "Bilasipara",
      "Other Locality / Area",
    ],
    Diphu: [
      "Diphu Main Bazar",
      "Rongnihang",
      "Matipung",
      "Lumding Road",
      "Other Locality / Area",
    ],
    Haflong: [
      "Haflong Lake Area",
      "Council Road",
      "Main Market",
      "Jatinga Area",
      "Other Locality / Area",
    ],
  },

  Meghalaya: {
    Shillong: [
      "Police Bazar (PB)",
      "Laitumkhrah",
      "Laban",
      "Mawlai",
      "Polo Ground",
      "Nongthymai",
      "Risa Colony",
      "Malki",
      "Cleve Colony",
      "Upper Shillong (Elephant Falls)",
      "NEHU Campus Area",
      "Mawprem",
      "Laban & Last Stop",
      "Rynjah & Lapalang",
      "Other Locality / Area",
    ],
    Tura: [
      "Tura Supermarket",
      "Hawakhana",
      "Araimile",
      "Dobasipara",
      "Chandmari",
      "Rongram",
      "Other Locality / Area",
    ],
    Jowai: [
      "Iawmusiang",
      "Ladthalaboh",
      "Mynthong",
      "Mihmyntdu",
      "Other Locality / Area",
    ],
    Nongpoh: [
      "Nongpoh Main Market",
      "Pahamsyiem",
      "Byrnihat Industrial Area",
      "Other Locality / Area",
    ],
    Cherrapunjee: [
      "Sohra Market",
      "Nongrim",
      "Mawsmai",
      "Khliehshnong",
      "Other Locality / Area",
    ],
  },

  "Arunachal Pradesh": {
    Itanagar: [
      "Ganga Market",
      "Bank Tinali",
      "Civil Secretariat Area",
      "Zero Point",
      "E-Sector",
      "Chandranagar",
      "Nirjuli (NERIST)",
      "Naharlagun (Helipad Road)",
      "Banderdewa",
      "Other Locality / Area",
    ],
    Naharlagun: [
      "Main Market",
      "Helipad Area",
      "Model Village",
      "Barapani",
      "Railway Colony",
      "Other Locality / Area",
    ],
    Tawang: [
      "Old Market",
      "New Market",
      "Monastery Road",
      "DC Office Area",
      "Other Locality / Area",
    ],
    Pasighat: [
      "Pasighat Market",
      "Medical Colony",
      "Gumin Nagar",
      "CHF Area",
      "Other Locality / Area",
    ],
    Ziro: [
      "Hapoli (Main Town)",
      "Old Ziro",
      "Biiri",
      "Tarang",
      "Other Locality / Area",
    ],
  },

  Manipur: {
    Imphal: [
      "Thangal Bazaar",
      "Paona Bazaar",
      "Khuman Lampak",
      "Lamphelpat",
      "Uripok",
      "Singjamei",
      "Kwakeithel",
      "Chingmeirong",
      "Mantripukhri",
      "RIMS Road",
      "Babupara",
      "Other Locality / Area",
    ],
    Churachandpur: [
      "Tuibong",
      "New Lamka",
      "IB Road",
      "Tedim Road",
      "Other Locality / Area",
    ],
    Thoubal: [
      "Thoubal Bazar",
      "Wangjing",
      "Kakching",
      "Other Locality / Area",
    ],
    Ukhrul: [
      "Viewland",
      "Wino Bazaar",
      "Dungrei",
      "Phungreitang",
      "Other Locality / Area",
    ],
  },

  Mizoram: {
    Aizawl: [
      "Bara Bazar",
      "Zarkawt",
      "Chanmari",
      "Khatla",
      "Mission Veng",
      "Bawngkawn",
      "Dinthar",
      "Tuikual",
      "Ramhlun",
      "Kulawn",
      "MZU Campus (Tanhril)",
      "Other Locality / Area",
    ],
    Lunglei: [
      "Venglai",
      "Bazar Veng",
      "Rahsi Veng",
      "Sazaikawn",
      "Other Locality / Area",
    ],
    Champhai: [
      "Vengthlang",
      "Kahrawt",
      "Veng Sang",
      "Zote",
      "Other Locality / Area",
    ],
  },

  Nagaland: {
    Dimapur: [
      "Hongkong Market",
      "City Tower",
      "Purana Bazar",
      "Duncan Basti",
      "Chumukedima",
      "Walford",
      "Padum Pukhuri",
      "Kacharigaon",
      "Notun Bosti",
      "Other Locality / Area",
    ],
    Kohima: [
      "Razhu Point",
      "PR Hill",
      "High School Area",
      "Ministers Hill",
      "Chandmari",
      "Midland",
      "BOC Area",
      "AG Colony",
      "Lerie",
      "Other Locality / Area",
    ],
    Mokokchung: [
      "Main Town",
      "Alempang",
      "Arkong",
      "Sangtemla",
      "Yimyu",
      "Other Locality / Area",
    ],
  },

  Sikkim: {
    Gangtok: [
      "MG Marg",
      "Tadong",
      "Deorali",
      "Ranipool",
      "Development Area",
      "Bojoghari",
      "Lal Bazar",
      "Arithang",
      "Sichey",
      "Other Locality / Area",
    ],
    Namchi: [
      "Central Park",
      "Char Dham Road",
      "Boomtar",
      "Assangthang",
      "Other Locality / Area",
    ],
    Gyalshing: [
      "Gyalshing Bazar",
      "Pelling",
      "Yuksom",
      "Other Locality / Area",
    ],
  },

  Tripura: {
    Agartala: [
      "Battala",
      "Golbazar",
      "Radhanagar",
      "Banamalipur",
      "Krishnanagar",
      "GB Hospital Area",
      "Indranagar",
      "Ramnagar",
      "Dhaleswar",
      "Amtali (Tripura Univ)",
      "Other Locality / Area",
    ],
    Dharmanagar: [
      "Main Market",
      "Station Road",
      "Nayapara",
      "Deoracherra",
      "Other Locality / Area",
    ],
    Udaipur: [
      "Matabari",
      "Central Market",
      "Rajbari",
      "Jamjuri",
      "Other Locality / Area",
    ],
  },
};

export const NE_STATE_NAMES = Object.keys(NORTHEAST_LOCATIONS);

export function getCitiesForState(state: string): string[] {
  const stateData = NORTHEAST_LOCATIONS[state];
  if (!stateData) return ["Guwahati", "Shillong", "Other City"];
  return Object.keys(stateData);
}

export function getLocalitiesForCity(state: string, city: string): string[] {
  const stateData = NORTHEAST_LOCATIONS[state];
  if (!stateData) return ["Main Area", "Other Locality / Area"];
  const localities = stateData[city];
  if (!localities) return ["Main Town Area", "Other Locality / Area"];
  return localities;
}
