-- Final Dummy Data for Discover Assam Database

-- News Table
INSERT INTO news (title, category, content, author, source, published_date, image_urls, tags, views_count) VALUES
('Kaziranga National Park Celebrates Conservation Success', 'Wildlife', 'Kaziranga National Park reports significant increase in one-horned rhinoceros population...', 'Rajesh Kumar', 'Assam Tribune', '2024-02-15 10:30:00', 'kaziranga_news1.jpg,kaziranga_news2.jpg', 'Wildlife, Conservation, Rhino', 1245),
('Bihu Festival Brings Assam Together', 'Culture', 'Annual Bihu festival showcases rich cultural heritage of Assam...', 'Priya Sharma', 'Northeast Today', '2024-04-14 09:15:00', 'bihu_festival1.jpg,bihu_festival2.jpg', 'Culture, Festival, Tradition', 2345),
('Assam Tea Wins International Awards', 'Business', 'Assam tea gardens receive global recognition for quality and sustainability...', 'Arun Baruah', 'Economic Times', '2024-01-20 14:45:00', 'tea_award1.jpg,tea_award2.jpg', 'Tea, Business, Agriculture', 987),
('New Wildlife Corridor Established', 'Environment', 'Government creates new wildlife corridor to protect endangered species...', 'Deepa Bora', 'Green News', '2024-03-10 11:20:00', 'wildlife_corridor1.jpg,wildlife_corridor2.jpg', 'Wildlife, Conservation, Environment', 678),
('Majuli: World\'s Largest River Island', 'Tourism', 'Majuli continues to attract global tourists with its unique culture...', 'Nayan Sharma', 'Travel Magazine', '2024-02-05 16:30:00', 'majuli_tourism1.jpg,majuli_tourism2.jpg', 'Tourism, Culture, River Island', 1567),
('Tech Startups Emerging in Guwahati', 'Business', 'Guwahati becoming a hub for technology and innovation...', 'Vikram Das', 'Business Standard', '2024-01-15 13:40:00', 'startup_guwahati1.jpg,startup_guwahati2.jpg', 'Technology, Startup, Business', 845),
('Traditional Handicrafts of Assam', 'Culture', 'Exploring the rich handicraft traditions of Assam...', 'Mridul Gogoi', 'Cultural Digest', '2024-03-25 10:10:00', 'handicraft1.jpg,handicraft2.jpg', 'Culture, Art, Tradition', 456),
('Brahmaputra River Ecosystem', 'Environment', 'Importance of Brahmaputra River ecosystem and conservation efforts...', 'Ranjita Devi', 'Nature Journal', '2024-02-28 15:15:00', 'brahmaputra1.jpg,brahmaputra2.jpg', 'River, Environment, Ecology', 723),
('Assam\'s Indigenous Music Traditions', 'Culture', 'Preserving and promoting indigenous musical heritage...', 'Jyoti Prasad', 'Music World', '2024-04-05 12:45:00', 'music_tradition1.jpg,music_tradition2.jpg', 'Music, Culture, Tradition', 567),
('Sustainable Tourism in Northeast', 'Tourism', 'Initiatives for sustainable and responsible tourism in Assam...', 'Bimal Sarma', 'Travel Insights', '2024-01-30 17:20:00', 'sustainable_tourism1.jpg,sustainable_tourism2.jpg', 'Tourism, Sustainability, Travel', 912);

-- Directory Table
INSERT INTO directory (business_name, category, subcategory, description, address, district, contact_number, email, website, latitude, longitude, working_hours, image_urls, rating, reviews_count) VALUES
('Brahmaputra Heritage Hotel', 'Hospitality', 'Hotel', 'Luxury hotel with traditional Assamese hospitality', 'GS Road, Guwahati', 'Kamrup', '+91 361 2456789', 'info@brahmaputrahotel.com', 'www.brahmaputrahotel.com', 26.1433, 91.7898, '24 Hours', 'hotel1.jpg,hotel2.jpg', 4.5, 245),
('Assam Tea Research Center', 'Agriculture', 'Research Institute', 'Leading tea research and development center', 'Tocklai, Jorhat', 'Jorhat', '+91 376 2304567', 'contact@teatestcenter.org', 'www.teatestcenter.org', 26.7833, 94.2167, '9 AM - 5 PM', 'tea_research1.jpg,tea_research2.jpg', 4.2, 87),
('Northeast Handicrafts Emporium', 'Retail', 'Handicraft Store', 'Authentic Assamese handicrafts and traditional products', 'Fancy Bazaar, Guwahati', 'Kamrup', '+91 361 2547890', 'sales@nehandicrafts.com', 'www.nehandicrafts.com', 26.1833, 91.7833, '10 AM - 8 PM', 'handicraft_store1.jpg,handicraft_store2.jpg', 4.7, 156),
('Guwahati Medical Center', 'Healthcare', 'Hospital', 'Multi-specialty hospital with advanced medical facilities', 'Dispur, Guwahati', 'Kamrup', '+91 361 2632281', 'info@guwahatimedical.com', 'www.guwahatimedical.com', 26.1417, 91.7833, '24 Hours', 'hospital1.jpg,hospital2.jpg', 4.3, 312),
('Assam Tourism Development Corporation', 'Professional Services', 'Tourism Board', 'Official tourism promotion and development organization', 'Paltan Bazaar, Guwahati', 'Kamrup', '+91 361 2547890', 'info@assamtourism.gov.in', 'www.assamtourism.gov.in', 26.1833, 91.7833, '9 AM - 6 PM', 'tourism_office1.jpg,tourism_office2.jpg', 4.0, 98),
('Kaziranga Wildlife Conservation Center', 'Professional Services', 'Conservation', 'Wildlife research and conservation organization', 'Kaziranga, Golaghat', 'Golaghat', '+91 3776 262421', 'contact@kaziranga.org', 'www.kaziranga.org', 26.5962, 93.0095, '8 AM - 5 PM', 'wildlife_center1.jpg,wildlife_center2.jpg', 4.6, 76),
('Majuli Cultural Center', 'Arts', 'Cultural Institution', 'Preserving and promoting Majuli\'s unique culture', 'Majuli Island', 'Majuli', '+91 3775 262421', 'info@majuliculture.org', 'www.majuliculture.org', 26.9167, 94.1333, '10 AM - 6 PM', 'cultural_center1.jpg,cultural_center2.jpg', 4.4, 64),
('Northeast IT Solutions', 'Technology', 'IT Company', 'Leading technology and software solutions provider', 'Dispur, Guwahati', 'Kamrup', '+91 361 2547000', 'contact@neitsolutions.com', 'www.neitsolutions.com', 26.1417, 91.7833, '9 AM - 7 PM', 'it_company1.jpg,it_company2.jpg', 4.1, 45),
('Assam Organic Tea Company', 'Agriculture', 'Tea Producer', 'Organic tea production and export', 'Jorhat', 'Jorhat', '+91 376 2304500', 'sales@assamorganictea.com', 'www.assamorganictea.com', 26.7833, 94.2167, '9 AM - 6 PM', 'tea_company1.jpg,tea_company2.jpg', 4.5, 92),
('Guwahati Science Museum', 'Education', 'Museum', 'Interactive science and technology museum', 'Khanapara, Guwahati', 'Kamrup', '+91 361 2456000', 'info@guwahatimuseum.org', 'www.guwahatimuseum.org', 26.1333, 91.7833, '10 AM - 5 PM', 'science_museum1.jpg,science_museum2.jpg', 4.2, 67);

-- Jobs Table
INSERT INTO jobs (title, company, category, type, location, district, salary_min, salary_max, experience_min, experience_max, skills_required, job_description, responsibilities, qualifications, application_deadline, contact_email, views_count, applications_count) VALUES
('Software Engineer', 'Northeast IT Solutions', 'IT', 'Full-time', 'Guwahati', 'Kamrup', 400000, 800000, 2, 5, 'Python, React, Cloud Computing', 'Develop innovative software solutions', 'Design and implement software applications', 'B.Tech/MCA in Computer Science', '2024-05-15', 'careers@neitsolutions.com', 1245, 87),
('Wildlife Researcher', 'Kaziranga Wildlife Conservation Center', 'Wildlife', 'Full-time', 'Kaziranga', 'Golaghat', 300000, 600000, 1, 4, 'Wildlife Biology, Data Analysis, Field Research', 'Conduct wildlife conservation research', 'Field studies, Data collection and analysis', 'M.Sc in Wildlife Biology or related field', '2024-04-30', 'research@kaziranga.org', 678, 45),
('Tourism Marketing Manager', 'Assam Tourism Development Corporation', 'Tourism', 'Government', 'Guwahati', 'Kamrup', 500000, 800000, 3, 7, 'Digital Marketing, Tourism Management', 'Develop and implement tourism marketing strategies', 'Create marketing campaigns, Manage digital platforms', 'MBA in Tourism or Marketing', '2024-05-10', 'careers@assamtourism.gov.in', 912, 56),
('Tea Research Scientist', 'Assam Tea Research Center', 'Agriculture', 'Full-time', 'Jorhat', 'Jorhat', 350000, 700000, 2, 6, 'Agricultural Science, Research Methodology', 'Conduct advanced tea research and development', 'Laboratory research, Field trials', 'Ph.D or M.Sc in Agricultural Science', '2024-04-25', 'careers@teatestcenter.org', 456, 32),
('Cultural Heritage Curator', 'Majuli Cultural Center', 'Culture', 'Full-time', 'Majuli', 'Majuli', 250000, 500000, 1, 4, 'Cultural Studies, Museum Management', 'Preserve and promote Majuli\'s cultural heritage', 'Artifact management, Exhibition curation', 'MA in Cultural Studies or Anthropology', '2024-05-05', 'careers@majuliculture.org', 345, 23),
('Healthcare Administrator', 'Guwahati Medical Center', 'Healthcare', 'Full-time', 'Guwahati', 'Kamrup', 450000, 750000, 3, 6, 'Hospital Management, Healthcare Administration', 'Manage hospital operations and administration', 'Staff management, Resource allocation', 'MBA in Healthcare Management', '2024-04-20', 'hr@guwahatimedical.com', 567, 41),
('Organic Tea Production Manager', 'Assam Organic Tea Company', 'Agriculture', 'Full-time', 'Jorhat', 'Jorhat', 400000, 700000, 2, 5, 'Agricultural Management, Organic Farming', 'Oversee organic tea production processes', 'Quality control, Production planning', 'B.Sc in Agriculture or related field', '2024-05-01', 'careers@assamorganictea.com', 234, 19),
('IT Sales Executive', 'Northeast IT Solutions', 'IT', 'Full-time', 'Guwahati', 'Kamrup', 300000, 600000, 1, 3, 'Sales, Technical Knowledge, Communication', 'Sell IT solutions to corporate clients', 'Client acquisition, Product demonstration', 'BCA/B.Tech with strong communication skills', '2024-04-28', 'sales@neitsolutions.com', 456, 34),
('Science Museum Educator', 'Guwahati Science Museum', 'Education', 'Full-time', 'Guwahati', 'Kamrup', 250000, 500000, 1, 4, 'Science Communication, Education', 'Develop and conduct science education programs', 'Interactive sessions, Exhibit management', 'M.Sc in Science or Education', '2024-05-07', 'education@guwahatimuseum.org', 189, 15),
('Handicraft Design Specialist', 'Northeast Handicrafts Emporium', 'Arts', 'Full-time', 'Guwahati', 'Kamrup', 300000, 550000, 2, 5, 'Design, Traditional Crafts, Art History', 'Design and develop traditional handicraft products', 'Product design, Cultural preservation', 'Diploma/Degree in Design or Fine Arts', '2024-04-22', 'design@nehandicrafts.com', 276, 22);

-- Optional: Add more tables as needed