import { NextResponse } from "next/server";

export async function GET() {
  const xsl = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
  xmlns:html="http://www.w3.org/TR/REC-html40"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>XML Sitemap | North East Connect SEO</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #1e293b;
            background-color: #f8fafc;
            margin: 0;
            padding: 40px 20px;
          }
          .container {
            max-width: 1040px;
            margin: 0 auto;
            background: #ffffff;
            border-radius: 16px;
            box-shadow: 0 4px 20px -2px rgba(0, 0, 0, 0.05), 0 2px 6px -1px rgba(0, 0, 0, 0.03);
            border: 1px solid #e2e8f0;
            overflow: hidden;
          }
          .header {
            padding: 32px;
            background: linear-gradient(135deg, #065f46 0%, #047857 50%, #0f766e 100%);
            color: #ffffff;
          }
          .header h1 {
            margin: 0 0 8px 0;
            font-size: 24px;
            font-weight: 800;
            letter-spacing: -0.025em;
          }
          .header p {
            margin: 0;
            font-size: 14px;
            opacity: 0.9;
            line-height: 1.5;
          }
          .badge {
            display: inline-block;
            background: rgba(255, 255, 255, 0.2);
            padding: 4px 10px;
            border-radius: 20px;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            margin-bottom: 12px;
            border: 1px solid rgba(255, 255, 255, 0.3);
          }
          .content {
            padding: 24px 32px;
          }
          .info {
            margin-bottom: 20px;
            font-size: 13px;
            color: #64748b;
          }
          .info a {
            color: #059669;
            text-decoration: none;
            font-weight: 600;
          }
          .info a:hover {
            text-decoration: underline;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            font-size: 13px;
          }
          th {
            background-color: #f1f5f9;
            color: #475569;
            text-align: left;
            padding: 12px 16px;
            font-weight: 700;
            text-transform: uppercase;
            font-size: 11px;
            letter-spacing: 0.05em;
            border-bottom: 2px solid #e2e8f0;
          }
          td {
            padding: 12px 16px;
            border-bottom: 1px solid #f1f5f9;
            color: #334155;
          }
          tr:hover td {
            background-color: #f8fafc;
          }
          td a {
            color: #059669;
            text-decoration: none;
            font-weight: 500;
          }
          td a:hover {
            text-decoration: underline;
            color: #047857;
          }
          .count-badge {
            background-color: #ecfdf5;
            color: #065f46;
            font-weight: 700;
            padding: 2px 8px;
            border-radius: 6px;
            font-size: 12px;
            display: inline-block;
          }
          .footer {
            padding: 20px 32px;
            background-color: #f8fafc;
            border-top: 1px solid #e2e8f0;
            font-size: 12px;
            color: #94a3b8;
            text-align: center;
          }
          .footer a {
            color: #059669;
            text-decoration: none;
          }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <div class="badge">Rank Math Style XML Sitemap</div>
            <h1>North East Connect XML Sitemap</h1>
            <p>Generated by North East Connect SEO Engine. This sitemap facilitates indexing by Google, Bing, Yahoo, and search crawlers.</p>
          </div>
          <div class="content">
            <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
              <p class="info">
                This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sub-sitemaps. Click any sitemap to inspect its URLs.
              </p>
              <table>
                <thead>
                  <tr>
                    <th width="75%">Sitemap Feed</th>
                    <th width="25%">Last Modified (UTC)</th>
                  </tr>
                </thead>
                <tbody>
                  <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                    <xsl:variable name="sitemapUrl" select="sitemap:loc"/>
                    <tr>
                      <td>
                        <a href="{$sitemapUrl}"><xsl:value-of select="sitemap:loc"/></a>
                      </td>
                      <td>
                        <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,8)))"/>
                      </td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:if>
            <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
              <p class="info">
                This sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
                <xsl:if test="sitemap:urlset/sitemap:url[1]/sitemap:loc">
                  &#160;| <a href="/sitemap_index.xml">&#8592; Back to Master Sitemap Index</a>
                </xsl:if>
              </p>
              <table>
                <thead>
                  <tr>
                    <th width="60%">Page URL</th>
                    <th width="15%">Priority</th>
                    <th width="10%">Frequency</th>
                    <th width="15%">Last Modified</th>
                  </tr>
                </thead>
                <tbody>
                  <xsl:for-each select="sitemap:urlset/sitemap:url">
                    <xsl:variable name="itemUrl" select="sitemap:loc"/>
                    <tr>
                      <td>
                        <a href="{$itemUrl}"><xsl:value-of select="sitemap:loc"/></a>
                      </td>
                      <td>
                        <span class="count-badge"><xsl:value-of select="sitemap:priority"/></span>
                      </td>
                      <td>
                        <xsl:value-of select="sitemap:changefreq"/>
                      </td>
                      <td>
                        <xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,8)))"/>
                      </td>
                    </tr>
                  </xsl:for-each>
                </tbody>
              </table>
            </xsl:if>
          </div>
          <div class="footer">
            Powered by <a href="https://northeastconnect.in">North East Connect</a> &#8226; Ranked &amp; Optimized for Northeast India
          </div>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>`;

  return new NextResponse(xsl, {
    status: 200,
    headers: {
      "Content-Type": "text/xsl; charset=utf-8",
      "Cache-Control": "public, s-maxage=86400, stale-while-revalidate=86400",
    },
  });
}
