-- Continued Dummy Data for Discover Assam Database

-- Adventure Table
INSERT INTO adventure (name, type, description, location, district, difficulty_level, duration, price, includes, excludes, age_restrictions, fitness_level, best_season, image_urls, contact_info) VALUES
('Brahmaputra River Rafting', 'River Rafting', 'Exciting white water rafting experience', 'Tezpur', 'Sonitpur', 'Intermediate', '1 Day', 2500.00, 'Safety gear, Instructor, Lunch', 'Personal expenses, Transport', '12-45 years', 'Moderate fitness', 'October-April', 'rafting1.jpg,rafting2.jpg', '+91 3712 224455'),
('Kaziranga Elephant Safari', 'Wildlife Safari', 'Guided safari through Kaziranga National Park', 'Golaghat', 'Golaghat', 'Easy', '3 Hours', 1500.00, 'Elephant ride, Guide, Entry fees', 'Personal expenses, Meals', '8-60 years', 'Basic fitness', 'November-April', 'elephant_safari1.jpg,elephant_safari2.jpg', '+91 3776 262421'),
('Trekking in Dzukou Valley', 'Trekking', 'Scenic mountain trek near Assam border', 'Dimapur', 'Dimapur', 'Advanced', '2 Days', 4000.00, 'Camping gear, Guide, Meals', 'Personal equipment, Transport', '18-45 years', 'High fitness', 'October-March', 'dzukou1.jpg,dzukou2.jpg', '+91 3862 248890'),
('Manas National Park Jeep Safari', 'Wildlife Safari', 'Explore diverse wildlife in Manas', 'Baksa', 'Baksa', 'Easy', '4 Hours', 2000.00, 'Jeep, Guide, Entry fees', 'Personal expenses, Meals', '6-65 years', 'Basic fitness', 'November-April', 'manas_safari1.jpg,manas_safari2.jpg', '+91 3666 274037'),
('Paragliding in Haflong', 'Paragliding', 'Aerial view of Assam\'s hill station', 'Haflong', 'Dima Hasao', 'Advanced', '1 Day', 5000.00, 'Equipment, Instructor, Safety gear', 'Personal expenses, Transport', '18-40 years', 'High fitness', 'October-March', 'paragliding1.jpg,paragliding2.jpg', '+91 3868 224455'),
('Nameri River Camping', 'Camping', 'Riverside camping and nature experience', 'Sonitpur', 'Sonitpur', 'Intermediate', '2 Days', 3500.00, 'Tent, Meals, Guide', 'Personal equipment, Transport', '12-50 years', 'Moderate fitness', 'October-March', 'nameri_camping1.jpg,nameri_camping2.jpg', '+91 3712 225240'),
('Cycling Tour of Tea Gardens', 'Cycling', 'Scenic bicycle tour through Assam tea estates', 'Jorhat', 'Jorhat', 'Easy', '1 Day', 1800.00, 'Bicycle, Guide, Refreshments', 'Personal expenses, Transport', '15-55 years', 'Basic fitness', 'November-February', 'tea_cycling1.jpg,tea_cycling2.jpg', '+91 376 2304567'),
('Majuli Island Exploration', 'Cultural Adventure', 'Explore unique river island culture', 'Majuli', 'Majuli', 'Easy', '1 Day', 1200.00, 'Guide, Local interactions, Lunch', 'Personal expenses, Transport', '8-65 years', 'Basic fitness', 'November-March', 'majuli1.jpg,majuli2.jpg', '+91 3775 262421'),
('Dibru-Saikhowa Nature Walk', 'Trekking', 'Guided nature walk in unique ecosystem', 'Tinsukia', 'Tinsukia', 'Intermediate', '4 Hours', 1500.00, 'Guide, Entry fees, Water', 'Personal expenses, Meals', '12-50 years', 'Moderate fitness', 'November-March', 'dibru_walk1.jpg,dibru_walk2.jpg', '+91 3775 244148'),
('Pobitora Wildlife Photography Tour', 'Wildlife Safari', 'Specialized wildlife photography expedition', 'Morigaon', 'Morigaon', 'Easy', '6 Hours', 3000.00, 'Guide, Entry fees, Photography tips', 'Personal equipment, Meals', '15-65 years', 'Basic fitness', 'November-April', 'pobitora_photo1.jpg,pobitora_photo2.jpg', '+91 3678 225240');

-- Packages Table
INSERT INTO packages (title, type, description, duration, original_price, discounted_price, discount_percentage, includes, excludes, itinerary, locations_covered, best_time_to_visit, group_size, image_urls) VALUES
('Assam Wildlife Expedition', 'Wildlife', 'Comprehensive wildlife tour of Assam', '5 Days', 25000.00, 20000.00, 20, 'Accommodation, Meals, Safari, Guide', 'Personal expenses, Transport', 'Day 1: Kaziranga, Day 2: Manas, Day 3: Nameri, Day 4: Pobitora, Day 5: Return', 'Kaziranga, Manas, Nameri, Pobitora', 'November-April', '4-10 persons', 'wildlife_package1.jpg,wildlife_package2.jpg'),
('Cultural Heritage of Assam', 'Cultural', 'Explore Assam\'s rich cultural heritage', '4 Days', 20000.00, 16000.00, 20, 'Accommodation, Meals, Guide, Entry fees', 'Personal expenses, Transport', 'Day 1: Guwahati, Day 2: Majuli, Day 3: Sivasagar, Day 4: Return', 'Guwahati, Majuli, Sivasagar', 'October-March', '4-12 persons', 'culture_package1.jpg,culture_package2.jpg'),
('Tea Gardens and Leisure', 'Leisure', 'Relaxing tour of Assam\'s tea estates', '3 Days', 15000.00, 12000.00, 20, 'Accommodation, Meals, Tea Estate Tour', 'Personal expenses, Transport', 'Day 1: Jorhat, Day 2: Tea Garden, Day 3: Return', 'Jorhat, Tea Gardens', 'November-February', '2-8 persons', 'tea_package1.jpg,tea_package2.jpg'),
('Adventure in Assam', 'Adventure', 'Thrilling adventure experiences', '4 Days', 22000.00, 18000.00, 18, 'Accommodation, Meals, Adventure Activities', 'Personal expenses, Transport', 'Day 1: Rafting, Day 2: Trekking, Day 3: Safari, Day 4: Return', 'Tezpur, Haflong, Manas', 'October-March', '4-10 persons', 'adventure_package1.jpg,adventure_package2.jpg'),
('Honeymoon in Northeast', 'Honeymoon', 'Romantic getaway in Assam and surroundings', '5 Days', 30000.00, 24000.00, 20, 'Accommodation, Meals, Romantic Activities', 'Personal expenses, Transport', 'Day 1: Guwahati, Day 2: Shillong, Day 3: Cherrapunji, Day 4: Kaziranga, Day 5: Return', 'Guwahati, Shillong, Kaziranga', 'October-March', '2 persons', 'honeymoon_package1.jpg,honeymoon_package2.jpg'),
('Family Fun in Assam', 'Family', 'Family-friendly tour of Assam', '4 Days', 18000.00, 15000.00, 17, 'Accommodation, Meals, Family Activities', 'Personal expenses, Transport', 'Day 1: Guwahati, Day 2: Manas, Day 3: Kaziranga, Day 4: Return', 'Guwahati, Manas, Kaziranga', 'November-February', '4-6 persons', 'family_package1.jpg,family_package2.jpg'),
('Spiritual Journey', 'Cultural', 'Explore spiritual sites of Assam', '3 Days', 16000.00, 13000.00, 19, 'Accommodation, Meals, Temple Visits', 'Personal expenses, Transport', 'Day 1: Guwahati, Day 2: Hajo, Day 3: Return', 'Guwahati, Hajo', 'October-March', '4-12 persons', 'spiritual_package1.jpg,spiritual_package2.jpg'),
('Brahmaputra River Cruise', 'Leisure', 'Scenic river cruise experience', '2 Days', 12000.00, 10000.00, 17, 'Cruise, Meals, Guided Tour', 'Personal expenses, Transport', 'Day 1: Cruise, Day 2: Return', 'Guwahati River Route', 'November-February', '10-20 persons', 'river_cruise1.jpg,river_cruise2.jpg'),
('Photography Expedition', 'Adventure', 'Capture Assam\'s natural beauty', '4 Days', 20000.00, 16000.00, 20, 'Accommodation, Guide, Photography Workshops', 'Personal equipment, Transport', 'Day 1: Kaziranga, Day 2: Manas, Day 3: Majuli, Day 4: Return', 'Kaziranga, Manas, Majuli', 'November-March', '4-8 persons', 'photo_expedition1.jpg,photo_expedition2.jpg'),
('Tribal Culture Tour', 'Cultural', 'Explore indigenous tribes of Assam', '5 Days', 25000.00, 20000.00, 20, 'Accommodation, Meals, Tribal Interactions', 'Personal expenses, Transport', 'Day 1: Guwahati, Day 2: Kokrajhar, Day 3: Dima Hasao, Day 4: Karbi Anglong, Day 5: Return', 'Guwahati, Kokrajhar, Dima Hasao', 'October-March', '4-10 persons', 'tribal_tour1.jpg,tribal_tour2.jpg');

-- Would you like me to continue with the remaining tables?